name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: ["0.14.0"]
        os: [macos-latest, windows-latest]
        include:
          - zig-version: "0.14.0"
            os: ubuntu-latest
            check-format: true

          - zig-version: "master"
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - if: ${{ matrix.check-format }}
        name: Check Formatting
        run: zig fmt --ast-check --check .

      - name: Build
        run: zig build --summary all
